import AdminEventsPanel from "../components/AdminEventsPanel";

function AdminPage() {
  return (
    <div>
      <h1 style={{ fontSize: 24, marginBottom: 12 }}>Admin Events</h1>
      <p style={{ fontSize: 13, color: "#9ca3af", marginBottom: 16 }}>
        This view shows lightweight analytics events generated by the chatbot,
        including messages, escalations, and demo logins.
      </p>
      <AdminEventsPanel />
    </div>
  );
}

export default AdminPage;
